version: 2

sources:
  - name: RAW
    database: ecommerce
    schema: RAW

    tables:
      - name: raw_customers
      - name: raw_order_items
      - name: raw_orders
      - name: raw_products
      - name: raw_store_locations